name: flutter_fb
description: "A new Flutter project."

# ì•± ë²„ì „
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # ğŸ”¥ Firebase ê´€ë ¨ íŒ¨í‚¤ì§€
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.0

  # iOS ìŠ¤íƒ€ì¼ ì•„ì´ì½˜
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ê¶Œì¥ ë¦°íŠ¸ ê·œì¹™
  flutter_lints: ^5.0.0

flutter:
  # ğŸ“¦ ê¸°ë³¸ ë¨¸í‹°ë¦¬ì–¼ ì•„ì´ì½˜ ì‚¬ìš©
  uses-material-design: true

  # ğŸ–¼ï¸ í”„ë¡œì íŠ¸ì— í¬í•¨ëœ ì´ë¯¸ì§€ ë¦¬ì†ŒìŠ¤ (assets)
  assets:
    - assets/images/
    - assets/images/jobs/
    - assets/images/items/


    # ì˜ˆ: assets/images/character1.png
    #     assets/images/character2.png
    #     assets/images/no_image.png

  # âœï¸ (ì„ íƒ) ì»¤ìŠ¤í…€ í°íŠ¸ ì¶”ê°€ ì˜ˆì‹œ
  # fonts:
  #   - family: NanumSquare
  #     fonts:
  #       - asset: assets/fonts/NanumSquare-Regular.ttf
  #       - asset: assets/fonts/NanumSquare-Bold.ttf
  #         weight: 700
