name: flutter_fb
description: "A new Flutter project."

# ì•± ë²„ì „
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # ğŸ”¥ Firebase ê´€ë ¨ íŒ¨í‚¤ì§€
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2

  # iOS ìŠ¤íƒ€ì¼ ì•„ì´ì½˜
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  intl: ^0.20.2
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ê¶Œì¥ ë¦°íŠ¸ ê·œì¹™
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # ğŸ“‚ í°íŠ¸ ë° ì´ë¯¸ì§€ í´ë”
    - assets/fonts/
    - assets/images/
    - assets/images/jobs/
    - assets/images/items/

    # ğŸ”¹ ì£¼ìš” ì´ë¯¸ì§€
    - assets/images/logo_done.png
    - assets/images/logo_done_big.png
    - assets/images/fame.png
    - assets/images/sample_weapon.png

    # ğŸ”¹ ìŠ¤íƒ¯ ì•„ì´ì½˜ í´ë” ì „ì²´
    - assets/images/stat/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
        - asset: assets/fonts/Pretendard-Medium.ttf
        - asset: assets/fonts/Pretendard-SemiBold.ttf
        - asset: assets/fonts/Pretendard-Bold.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_done_big.png
  android: true
  ios: true
  web: false
